create table if not exists users
(
    user_id  long generated by default as identity primary key,
    login    varchar(100) UNIQUE,
    name     varchar(200),
    email    varchar(300) UNIQUE,
    birthday date
);

create table if not exists friendship
(
    user_id   long not null references users (user_id),
    friend_id long not null references users (user_id),
    status    boolean
);

create table if not exists films
(
    film_id      long generated by default as identity primary key,
    name         varchar(200),
    description  varchar(300),
    MPA_id       long,
    release_date date,
    rate         integer,
    duration     integer
);

create table if not exists film_likes
(
    film_id long not null references films (film_id),
    user_id long not null references users (user_id)
);

create table if not exists MPA
(
    MPA_id long generated by default as identity primary key,
    name   varchar(200) NOT NULL
);

create table if not exists genre
(
    genre_id long generated by default as identity primary key,
    name     varchar(200) NOT NULL
);


create table if not exists film_genre
(
    film_id  long not null references films (film_id),
    genre_id long not null references genre (genre_id)
);